# Generated by Django 4.0.5 on 2022-09-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
